# Generated by Django 5.1.4 on 2024-12-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventoryhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='threshold',
            field=models.IntegerField(default=10),
        ),
    ]
