# Generated by Django 5.1.4 on 2024-12-30 10:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_threshold'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryhistory',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='product',
            name='threshold',
            field=models.IntegerField(default=10, help_text='Reorder level. Default is 10.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
